# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.srcs/sources_1/bd/design_1/ip/design_1_MME_0_0/design_1_MME_0_0.xci
# IP: The module: 'design_1_MME_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/bd_cd85.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85 || ORIG_REF_NAME==bd_cd85} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_0/bd_cd85_AXI4Stream_DataMover_MM2S_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_DataMover_MM2S_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_DataMover_MM2S_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_1/bd_cd85_AXI4Stream_Datamover_S2MM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_Datamover_S2MM_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_Datamover_S2MM_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_2/bd_cd85_AXI4Stream_PacketFetcher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_PacketFetcher_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_PacketFetcher_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_3/bd_cd85_AXI4Stream_Packetizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_Packetizer_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_Packetizer_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_4/bd_cd85_AXI4Stream_multicobs_upsizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_multicobs_upsizer_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_multicobs_upsizer_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_5/bd_cd85_axi_datamover_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axi_datamover_0_0 || ORIG_REF_NAME==bd_cd85_axi_datamover_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_6/bd_cd85_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axis_dwidth_converter_0_0 || ORIG_REF_NAME==bd_cd85_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_8/bd_cd85_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_xbar_0 || ORIG_REF_NAME==bd_cd85_xbar_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_7/bd_cd85_axis_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axis_interconnect_0_0 || ORIG_REF_NAME==bd_cd85_axis_interconnect_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_10/bd_cd85_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_xbar_1 || ORIG_REF_NAME==bd_cd85_xbar_1} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_9/bd_cd85_axis_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axis_interconnect_1_0 || ORIG_REF_NAME==bd_cd85_axis_interconnect_1_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_12/bd_cd85_AXI4Stream_TDEST_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_TDEST_filter_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_TDEST_filter_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_11/bd_cd85_s_arb_req_suppress_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_s_arb_req_suppress_concat_0 || ORIG_REF_NAME==bd_cd85_s_arb_req_suppress_concat_0} -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_5/bd_cd85_axi_datamover_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cd85_axi_datamover_0_0 || ORIG_REF_NAME==bd_cd85_axi_datamover_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_5/bd_cd85_axi_datamover_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cd85_axi_datamover_0_0 || ORIG_REF_NAME==bd_cd85_axi_datamover_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_8/bd_cd85_xbar_0_ooc.xdc

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_10/bd_cd85_xbar_1_ooc.xdc

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/bd_cd85_ooc.xdc

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.srcs/sources_1/bd/design_1/ip/design_1_MME_0_0/design_1_MME_0_0.xci
# IP: The module: 'design_1_MME_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/bd_cd85.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85 || ORIG_REF_NAME==bd_cd85} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_0/bd_cd85_AXI4Stream_DataMover_MM2S_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_DataMover_MM2S_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_DataMover_MM2S_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_1/bd_cd85_AXI4Stream_Datamover_S2MM_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_Datamover_S2MM_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_Datamover_S2MM_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_2/bd_cd85_AXI4Stream_PacketFetcher_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_PacketFetcher_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_PacketFetcher_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_3/bd_cd85_AXI4Stream_Packetizer_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_Packetizer_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_Packetizer_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_4/bd_cd85_AXI4Stream_multicobs_upsizer_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_multicobs_upsizer_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_multicobs_upsizer_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_5/bd_cd85_axi_datamover_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axi_datamover_0_0 || ORIG_REF_NAME==bd_cd85_axi_datamover_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_6/bd_cd85_axis_dwidth_converter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axis_dwidth_converter_0_0 || ORIG_REF_NAME==bd_cd85_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_8/bd_cd85_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_xbar_0 || ORIG_REF_NAME==bd_cd85_xbar_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_7/bd_cd85_axis_interconnect_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axis_interconnect_0_0 || ORIG_REF_NAME==bd_cd85_axis_interconnect_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_10/bd_cd85_xbar_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_xbar_1 || ORIG_REF_NAME==bd_cd85_xbar_1} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_9/bd_cd85_axis_interconnect_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_axis_interconnect_1_0 || ORIG_REF_NAME==bd_cd85_axis_interconnect_1_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_12/bd_cd85_AXI4Stream_TDEST_filter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_AXI4Stream_TDEST_filter_0_0 || ORIG_REF_NAME==bd_cd85_AXI4Stream_TDEST_filter_0_0} -quiet] -quiet

# IP: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_11/bd_cd85_s_arb_req_suppress_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cd85_s_arb_req_suppress_concat_0 || ORIG_REF_NAME==bd_cd85_s_arb_req_suppress_concat_0} -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_5/bd_cd85_axi_datamover_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cd85_axi_datamover_0_0 || ORIG_REF_NAME==bd_cd85_axi_datamover_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_5/bd_cd85_axi_datamover_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cd85_axi_datamover_0_0 || ORIG_REF_NAME==bd_cd85_axi_datamover_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_8/bd_cd85_xbar_0_ooc.xdc

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/ip/ip_10/bd_cd85_xbar_1_ooc.xdc

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_MME_0_0/bd_0/bd_cd85_ooc.xdc
