# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mconsonni/Desktop/DESD/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.srcs/sources_1/bd/design_1/ip/design_1_AXI4Stream_CoarseExtensionCore_0_2/design_1_AXI4Stream_CoarseExtensionCore_0_2.xci
# IP: The module: 'design_1_AXI4Stream_CoarseExtensionCore_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mconsonni/Desktop/DESD/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_AXI4Stream_CoarseExtensionCore_0_2/src/timing_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_AXI4Stream_CoarseExtensionCore_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mconsonni/Desktop/DESD/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.srcs/sources_1/bd/design_1/ip/design_1_AXI4Stream_CoarseExtensionCore_0_2/design_1_AXI4Stream_CoarseExtensionCore_0_2.xci
# IP: The module: 'design_1_AXI4Stream_CoarseExtensionCore_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mconsonni/Desktop/DESD/Projects/TDC_Measurement_Setup/TDC_Measurement_Setup.gen/sources_1/bd/design_1/ip/design_1_AXI4Stream_CoarseExtensionCore_0_2/src/timing_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_AXI4Stream_CoarseExtensionCore_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
